version: '3.1'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/freecodetube.testingapp/public_html
      - apache2-conf:/etc/apache2
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  apache2-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./apache2-conf